language: php

cache:
  directories:
    - $HOME/.composer/cache
    
before_install:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
  
script:
  - (phpunit -c phpunit.xml)
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then php php-cs-fixer.phar fix -v --diff --dry-run ; fi

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
