language: php

cache:
  directories:
    - $HOME/.composer/cache
    
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs
  
script:
  - (cd tests ; phpunit -c phpunit.xml)
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then php php-cs-fixer.phar fix -v --diff --dry-run ; fi

after_script:
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: hhvm
    - php: 7
