<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LosLog\Module'                         => __DIR__ . '/Module.php',
  'LosLog\Log\AbstractLogger'             => __DIR__ . '/src/LosLog/Log/AbstractLogger.php',
  'LosLog\Log\EntityLogger'               => __DIR__ . '/src/LosLog/Log/EntityLogger.php',
  'LosLog\Log\ErrorLogger'                => __DIR__ . '/src/LosLog/Log/ErrorLogger.php',
  'LosLog\Log\LoggableObject'             => __DIR__ . '/src/LosLog/Log/LoggableObject.php',
  'LosLog\Log\SqlLogger'                  => __DIR__ . '/src/LosLog/Log/SqlLogger.php',
  'LosLog\Log\StaticLogger'               => __DIR__ . '/src/LosLog/Log/StaticLogger.php',
  'LosLog\Options\ModuleOptions'          => __DIR__ . '/src/LosLog/Options/ModuleOptions.php',
  'LosLogTests\Bootstrap'                 => __DIR__ . '/tests/Bootstrap.php',
  'LosLogTests\Log\EntityLoggerTest'      => __DIR__ . '/tests/LosLogTests/Log/EntityLoggerTest.php',
  'LosLogTests\Log\ErrorLoggerTest'       => __DIR__ . '/tests/LosLogTests/Log/ErrorLoggerTest.php',
  'LosLogTests\Log\SqlLoggerTest'         => __DIR__ . '/tests/LosLogTests/Log/SqlLoggerTest.php',
  'LosLogTests\Log\StaticLoggerTest'      => __DIR__ . '/tests/LosLogTests/Log/StaticLoggerTest.php',
  'LosLogTests\Options\ModuleOptionsTest' => __DIR__ . '/tests/LosLogTests/Options/ModuleOptionsTest.php',
);
