<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosLog\Log\AbstractLogger'    => __DIR__ . '/src/LosLog/Log/AbstractLogger.php',
    'LosLog\Log\EntityLogger'      => __DIR__ . '/src/LosLog/Log/EntityLogger.php',
    'LosLog\Log\ErrorLogger'       => __DIR__ . '/src/LosLog/Log/ErrorLogger.php',
    'LosLog\Log\Loggable'          => __DIR__ . '/src/LosLog/Log/Loggable.php',
    'LosLog\Log\LoggableObject'    => __DIR__ . '/src/LosLog/Log/LoggableObject.php',
    'LosLog\Log\SqlLogger'         => __DIR__ . '/src/LosLog/Log/SqlLogger.php',
    'LosLog\Log\StaticLogger'      => __DIR__ . '/src/LosLog/Log/StaticLogger.php',
    'LosLog\Options\ModuleOptions' => __DIR__ . '/src/LosLog/Options/ModuleOptions.php',
);
