<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosMiddleware\LosLog\AbstractLogger'                     => __DIR__ . '/src/AbstractLogger.php',
    'LosMiddleware\LosLog\ErrorLogger'                        => __DIR__ . '/src/ErrorLogger.php',
    'LosMiddleware\LosLog\Exception\InvalidArgumentException' => __DIR__ . '/src/Exception/InvalidArgumentException.php',
    'LosMiddleware\LosLog\ExceptionLogger'                    => __DIR__ . '/src/ExceptionLogger.php',
    'LosMiddleware\LosLog\Loggable'                           => __DIR__ . '/src/Loggable.php',
    'LosMiddleware\LosLog\LosLog'                             => __DIR__ . '/src/LosLog.php',
    'LosMiddleware\LosLog\LosLogFactory'                      => __DIR__ . '/src/LosLogFactory.php',
    'LosMiddleware\LosLog\StaticLogger'                       => __DIR__ . '/src/StaticLogger.php',
    'LosMiddleware\LosLog\Writer\Rollbar'                     => __DIR__ . '/src/Writer/Rollbar.php',
);
