<?php

namespace LosMiddleware\LosLog;

use Zend\Log\Logger;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 10:40:44.
 */
class ExceptionLoggerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExceptionLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ExceptionLogger();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LosMiddleware\LosLog\ExceptionLogger::registerHandlers
     *
     * @todo   Implement testRegisterHandlers().
     */
    public function testRegisterHandlers()
    {
        ExceptionLogger::registerHandlers('exception.log', '.');

        $logger = AbstractLogger::generateFileLogger('exception.log', '.')->getLogger();
        $writer = new \Zend\Log\Writer\Mock();
        $logger->addWriter($writer);

        //Ensures it's already registered
        $this->assertFalse(Logger::registerErrorHandler($logger));
    }
}
