<?php

namespace LosMiddleware\LosLog;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 10:24:09.
 */
class LoggableTest extends TestCase
{
    /**
     * @var Loggable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForTrait('LosMiddleware\LosLog\Loggable');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LosMiddleware\LosLog\Loggable::losLogMe
     */
    public function testLosLogMe()
    {
    }
}
