<?php

namespace LosMiddleware\LosLog;

use Zend\ServiceManager\ServiceManager;
use Zend\ServiceManager\Config;
use org\bovigo\vfs\vfsStream;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 10:24:11.
 */
class LosLogFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LosLogFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LosLogFactory();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LosMiddleware\LosLog\LosLogFactory::__invoke
     */
    public function test__invoke()
    {
        $root = vfsStream::setup('home');
        $file = vfsStream::url('home/static.log');

        $container = new ServiceManager(new Config([]));
        $container->setService('config', [
            'loslog' => [
                'log_dir' => 'home',
                'error_logger_file' => $file,
                'exception_logger_file' => $file,
                'static_logger_file' => $file,
            ],
        ]);
        $this->assertInstanceOf(LosLog::class, $this->object->__invoke($container));
    }
}
