<?php

namespace LosMiddleware\LosLog;

use org\bovigo\vfs\vfsStream;

class IncompleteTest
{
    public $prop = 1;
}

class Test
{
    use Loggable;

    public $prop = 2;
    public $test;

    public function __construct()
    {
        $this->test = new IncompleteTest();
    }

    public function __toString()
    {
        return (string) $this->prop;
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-02 at 10:24:11.
 */
class StaticLoggerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LosMiddleware\LosLog\StaticLogger::save
     */
    public function testSave()
    {
        $root = vfsStream::setup('home');
        $file = vfsStream::url('home/static.log');
        StaticLogger::save('teste', $file);
        $log = $root->getChild('home/static.log')->getContent();
        $this->assertNotFalse(strpos($log, 'teste'));
    }

    /**
     * @covers LosMiddleware\LosLog\StaticLogger::save
     * @covers LosMiddleware\LosLog\Loggable::losLogMe
     */
    public function testSaveObject()
    {
        $obj = new Test();
        $root = vfsStream::setup('home');
        $file = vfsStream::url('home/static.log');
        StaticLogger::save($obj, $file);
        $log = $root->getChild('home/static.log')->getContent();
        $this->assertNotFalse(strpos($log, 'Test'));
        $this->assertNotFalse(strpos($log, 'IncompleteTest'));
        $this->assertNotFalse(strpos($log, '"prop":{"type":"integer","content":2}'));
    }

    /**
     * @covers LosMiddleware\LosLog\StaticLogger::save
     */
    public function testSaveForZRay()
    {
        StaticLogger::save('teste', null);
    }
}
